### ISSUE TITLE
Automatically switch project when the loaded project changes in the Project view

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/Oxygen-Git-Plugin#10]
We have an editor variable called ${pdu} which can be expanded using the API to the current project. So we can expand this editor variable each time focus is gained in the git view to see if the current project folder changed and if it is a git project.

**Comment by AlexJitianu** [comment]
On the project change event, we could also look inside the *.xpr file and collect all the real folders referred inside logical folders. We could check them as well for GIT repositories.

**Comment by raducoravu** [comment]
Maybe on the first iteration we could look only at the project main folder.
Because we only support one working copy anyway..

**Comment by georgebina** [comment]
The other locations can be added in the drop down, so one can easily switch to such a repository.
