### ISSUE TITLE
Branch management - add a filter text field

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-git-plugin#103]
Sub-task of #42. Here we should focus on adding a filter text field before the branches tree and implement it's functionality. The branches tree should be filtered based on the provided text.

**Comment by AlexJitianu** [comment]
Code review:
1. I have filtered something and left the view. When I return with the focus in the tree, the model resets and presents all branches. The filter text is still there. When I return with the focus directly in the search field, the model also resets. In bots cases I expect the model to continue presenting the search results until I change or delete the filter.
