### ISSUE TITLE
Add a "Reset current branch to this commit" action in History view

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-git-plugin#109]
In the Git History table we should add a contextual action that allows resetting the current branch to the selected commit. This action should show a dialog that presents:
- the name of the current branch
- the commit to which to reset (ID and perhaps the message too)
- a combo box for the reset mode: soft, mixed, hard (with extra details for each entry)

The buttons should be "Reset" and "Cancel".

**Comment by kirkilj** [comment]
Hi Sorin, this feature is one of the many possible functions that can be applied to a commit in the history view. I listed some others in https://github.com/oxygenxml/oxygen-git-plugin/issues/94.

**Comment by sorincarbunaru** [comment]
Hi John,

Yes, I extracted it from there, for easier management. In time we will tackle more of them ;).

**Comment by sorincarbunaru** [comment]
UPDATE: for the reset mode, instead of a combo box, it's probably better to use a radio buttons group. This way you see all 3 modes at the first glance, and the interaction is faster with radio buttons than with drop-down menus.
