### ISSUE TITLE
Slow performance after upgrading to 2.3.0

### ISSUE THREAD

**Issue by mhowes82** [oxygenxml/oxygen-git-plugin#110]
Running Oxygen 22.1 with Git on Windows 10. After upgrading to version 2.3.0 of the plugin, opening files, particularly maps/topics, is extremely slow in Oxygen. I uninstalled the plugin and performance returned to normal.

**Comment by sorincarbunaru** [comment]
Um, I cannot reproduce this issue on my side. 

1. Did you notice the performance decrease on more than one repository? 
2. Where did you open the files from: Project view, DITA Maps Manager, the Open action from the context menu in Git Staging?
3. If you re-install the add-on, does the problem happen again? If yes, could you please extract the properties file from [log4j2.zip](https://github.com/oxygenxml/oxygen-git-plugin/files/5331944/log4j2.zip) to Oxygen's installation folder? This will enable full logging for the Git Client. After you restart Oxygen and you open a few documents, please add the "oxygenLog" folder from your Desktop to an archive and send it to us at support@oxygenxml.com for further investigations.

**Comment by sorincarbunaru** [comment]
4. Did you, by any chance, have the Git Branch Manager side-view shown? Do you have many branches (tens of branches)?

**Comment by sorincarbunaru** [comment]
@mhowes82, please let me know if version 2.3.1 seems to solve the performance issue.

**Comment by mhowes82** [comment]
I re-installed 2.3.1 and performance appears to be back to normal. Thanks for the quick fix!
