### ISSUE TITLE
'Cannot reach host', unless I launch Oxygen via Git Bash

### ISSUE THREAD

**Issue by elijahkull** [oxygenxml/oxygen-git-plugin#114]
I'm having an issue very similar to https://github.com/oxygenxml/oxygen-git-plugin/issues/34. When I launch Oxygen XML editor normally, the Git Staging add-on prompts me to enter an SSH passphrase. When I enter the passphrase and select OK, the prompt immediately returns and displays the error Cannot Reach Host.

If I launch Oxygen XML editor via Git Bash, the Git Staging add-on works as expected. It seems like launching it via Git Bash causes it to correctly look for the SSH key in the C:\Users\User.Name\.ssh directory. I'm not sure where it's looking when I launch Oxygen normally.

Is it possible to manually set the SSH key directory in the Git Staging add-on? Alternatively, how can I check which directory the add-on is looking for when Oxygen is launched normally?

**Comment by sorincarbunaru** [comment]
Hello,

1. No, it is not possible to change the `ssh` directory in the Git Client add-on.

2. To check the `ssh` directory you can download [log4j.zip](https://github.com/oxygenxml/oxygen-git-plugin/files/5558248/log4j.zip), extract the `log4j.properties` file inside Oxygen's installation folder, then restart Oxygen, and after you see the "Cannot reach host" message, look on you Desktop for an "oxygenLog" directory. In the "oxygen.log" file you should look for entries that start with "SSH resource path".

Have you tried the possible solutions proposed on #34?

By the way, what versions of Oxygen and Git Client add-on are you using?

All the best wishes!

**Comment by elijahkull** [comment]
Thank you, Sorin! I'm using version 22.1, build 2020100710 of Oxygen, and version 2.3.1 of Git Client.

I checked the oxygen.log file and found that it was looking to P:\ as the home directory. I'm not sure why it's looking there, because P:\ doesn't exist as a local or network drive. I ended up fixing it by going into Advanced System Settings > Environment Variables and adding a HOME variable with the %USERPROFILE% value.

It's working as expected now. Thanks again for your help!

**Comment by sorincarbunaru** [comment]
Hi Elihaj,

I have one curiosity, if I may... Were you trying to connect to a Git repo in  Team Foundation Server / Azure DevOps?  Someone wrote me about a similar problem (the "known_hosts" file keeps being generated in drive P:) and I remembered about your issue. They told me their repo is on Azure DevOps, and I wanted to see if the same applies to you.
