### ISSUE TITLE
Plugin perspective lacks an entry in Menu Shortcut Keys

### ISSUE THREAD

**Issue by davidpriest** [oxygenxml/oxygen-git-plugin#116]
Replicate in v2.3.1: 
* From any window, go to Menu > Options > Menu Shortcut Keys…. 

* Use the Filter box to search for "Git". No views of Git are found.

Expectation:
* Able to assign a keyboard shortcut to the "Git Staging" view.

* Use the Filter box to search for "Perspective". "Git Staging" is listed, along with many other views including "Archive Viewer", "Project", "Outline", etc. Many of these are views that can be displayed in the same pane as the Git Staging view. 

* Use the Filter box to search for "Git". An entry for the Menu > Tools > Git Client command should be listed in the "Tools" category, along with the many other tools that appear in that menu.

* If the Git plugin has other dockable views, I would expect them to be listed appropriately as well.

**Comment by sorincarbunaru** [comment]
Hello David!

Thank you for the feedback!

We already have an internal issue for setting shortcuts to the side-views contributed by our add-ons, and the issue is planned for the next development sprint. All the other points should be taken care of in this issue.

**Comment by sorincarbunaru** [comment]
This issue has been fixed and it will be available in Oxygen 23.1.

**Comment by sorincarbunaru** [comment]
Hi,

Just wanted to let you know that Oxygen 23.1 is now available, and it allows setting shortcuts to the action contributed by plugins.

Best wishes,
Sorin Carbunaru
