### ISSUE TITLE
Add ability to create and checkout a branch at the same time

### ISSUE THREAD

**Issue by jonathanhanna** [oxygenxml/oxygen-git-plugin#117]
When creating a new branch in the Branch Manager, it would be helpful if the new branch was automatically checked out after creation. It's really easy to forget to check out the branch after you created it. Basically, I'm asking for the `git checkout -b`  feature.

**Comment by sorincarbunaru** [comment]
Hello Jonathan! Thank you for your feedback! 

We will consider this for a future version. We will update this thread when the change will be publicly available 😄.

**Comment by sorincarbunaru** [comment]
This improvement has been implemented. We added a "Checkout branch" checkbox in the "Create branch" dialog, and the checkbox is selected by default.

We will release a new version of the Git Client sometime in the next 2-3 weeks. We will update this thread when we do it.

**Comment by jonathanhanna** [comment]
Thank you for adding this feature! I look forward to the new version!

**Comment by sorincarbunaru** [comment]
The new version, 2.5.0, is out now :).
