### ISSUE TITLE
When cloning a repository, pull all files contained in submodules

### ISSUE THREAD

**Issue by jonathanhanna** [oxygenxml/oxygen-git-plugin#118]
Currently, when you clone a repository that contains submodules, the submodule folders will be empty. This is confusing to authors. In order to get the files in the submodules, they either need to perform a `git clone --recurse-submodules <repo-url>` on the command line or use GitHub Desktop to clone the repository.

It would be helpful if there was an option to perform `git clone --recurse-submodules <repo-url>`  when cloning the repository (but making it author-friendly, of course 😄).

**Comment by AlexJitianu** [comment]
Hello,

Thank you for reporting this issue. I was thinking to set the `--recurse-submodules` by default. We could add a check box in the clone dialog, but I'm not sure what name we can give it to make it more user friendly. _"Recurse submodule"_ is not very intuitive to a person that is not accustomed with Git.... Please let me know your thoughts on the matter.

**Comment by AlexJitianu** [comment]
By the way, currently, we will initialize and update the submodule when you use the _Submodules_ action on the _Git Staging_ toolbar. You might give it as an workaround to the writers until we release a new version.

**Comment by jonathanhanna** [comment]
Setting `--recurse-submodules` as the default would be preferable. That would be less confusing and mimic the same behavior as GitHub Desktop. Additionally, it would be preferable for the Git plugin to automatically create a directory when cloning the repository (with the same name as the repository) instead of requiring the user to create a new empty directory.

I tried to initialize and update the submodule by using the _Submodules_ action as you suggested. However, I ran into a problem. When I switched to the submodule I wanted to initialize, I got the following error message:

> Submodule could not be loaded because of:
> \<submodule-url\>: Authentication is required but no CredentialsProvider has been registered.

I am not sure why I am getting this error or how to fix it since the Git plugin is not asking for any credentials. However, it is not a huge issue since I am still able to initialize the submodules on the command line or when using GitHub Desktop. And I'm assuming this issue will not appear when you add `--recurse-submodules` as the default when cloning 😁 .

**Comment by AlexJitianu** [comment]
Agree, we will set it automatically, just like GitHub Desktop does it. The exception is actually thrown by a {{git submodule update}} that is also executed when loading the submodule. We will fix that too.

**Comment by AlexJitianu** [comment]
The fix regarding the authentication will be available in the next release.

 Apparently, I've missed this question:
> I have one other question related to submodules. Are there any plans to provide the ability to add a submodule from the Git plugin? That is, providing a GUI-friendly way to perform git submodule add <submodule-url>?
I will add an internal feature request, but I don't think it will be done on the short term. When we prioritize features, we prefer the ones that will be used frequently by an user. Usually, our Git client is used by technical writers. Adding a submodule looks like a task perform by an information architect, a person that decides how to structure the projects, not by a technical writer. I'm not saying it's not an useful feature to have, just that our development resources are limited and it might take a while until we manage to implement it.

**Comment by jonathanhanna** [comment]
Thanks for adding this feature and fixing the authentication issue! I completely understand having to prioritize features. For now, I have been using template repositories that already have the submodules added. So far it is working well.

**Comment by sorincarbunaru** [comment]
Git Client 2.5.0 is out now and it has a fix for the submodule authentication 😄.
