### ISSUE TITLE
Enhancement: Viewing log for a specific directory

### ISSUE THREAD

**Issue by ahenket** [oxygenxml/oxygen-git-plugin#121]
When I request Git history on a directory I'm expecting to see the commit logs for that directory only. Instead I always get the full branch history.

Could that be updated so it works like in SVN or `git log .` on the command line? The thing with the command line is that it's either too much or too little (--online). This is where a UI could shine and make the difference.

**Comment by AlexJitianu** [comment]
Hello,
From my tests, it looks like it already does that. I've used the _Git->Show history_ action from the _Project view_'s contextual menu. The commits I see in the _History view_ all contain at least one resource from the directory I've invoked the action on. Of course, those commits might contain resources from other directories as well which makes it hard to identify the ones of interest. What would help here is to make the other resources grayed out.

**Comment by chrispy-snps** [comment]
I would like to see this enhancement too!

While I understand that the commits can contain activity for other files, it would be nice to somehow deemphasize the commit activity that is outside the current **file or directory** scope of interest.

**Comment by AlexJitianu** [comment]
Reading again the initial post, I think this is what @ahenket referred to as well. I too think it's worth doing it.

**Comment by AlexSmarandache15** [comment]
When showing the hisotry for a file, other files from the commit are grayed out.:
![image](https://user-images.githubusercontent.com/68815668/134148042-a9bcef1f-19f8-4656-9030-ddf57a06f073.png)

When showing the hisotry for a folder, files from commits that are outside the folder are grayed out.

**Comment by chrispy-snps** [comment]
Awesome, thank you!

Is it also possible to promote the relevant files to the top, e.g. by applying a two-factor sort (grayed status first, alphabetical second)?

**Comment by AlexSmarandache15** [comment]
Hello, @chrispy-snps! I'm happy that you liked it. I also changed the sorting so that the files whose history is seen appear at the top.
