### ISSUE TITLE
Release maintenance version 2.5.1

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-git-plugin#125]
- [x] Make sure the automated tests pass. Check Jenkins (https://jenkins-master.sync.ro/job/oxygen-git-plugin/).
- [x] Add the "What's New" list to **addon.xml**.
- [x] Tag the commit that will be the last one included in the release and push the tag to the remote repository.
- [x] Add the "What's New" list to the new release from GitHub. See https://github.com/oxygenxml/oxygen-git-plugin/releases.
- [x] Check the new version is available on the default update site.
- [x] Send e-mail to the users who agreed to be notified when what they requested has been implemented.
- [x] Update the forum threads where users requested things that have been implemented for the current release.
- [x] Promote the release on social media, oxygen-users list and DITA list.
- [x] Update internal version on Jenkins.

**Comment by kirkilj** [comment]
Right around the time I upgraded to 2.5.1, the Staging view started prompting me for a passphrase from a repo that's never needed it before. The interesting thing is that the Git History and Git Branch views are happy as can be.

![image](https://user-images.githubusercontent.com/128799/123197154-bd29f000-d470-11eb-83d7-8db6b0887bb2.png)

I'll continue to search if anything changed on my side, but I can't think of anything off-hand.

**Comment by kirkilj** [comment]
I downgraded to 2.5.0 and the problem went away.

**Comment by AlexJitianu** [comment]
Hi John,

Does this particular repository use a passphrase at all?

**Comment by kirkilj** [comment]
It never had a passphrase. GitBash didn't prompt for one either.

I'd be glad to test a new build.

**Comment by AlexJitianu** [comment]
Here it is: 
https://github.com/oxygenxml/oxygen-git-plugin/releases/download/2.5.2/oxygen-git-client-1.0.0-plugin.jar

**Comment by kirkilj** [comment]
Works like a champ! Thanks.

**Comment by kirkilj** [comment]
Maybe not. Now I'm seeing other authentication issues. Let me reboot and retest. Command line has no problems with authentication.

**Comment by kirkilj** [comment]
Reboot didn't help. I was using the one you emailed me. I don't know if the 2.5.2-draft is different, but I'll try that next.

**Comment by kirkilj** [comment]
The 2.5.2-draft works fine. The message no longer appears. Just curious, why does that message come up for the Staging view, but not for the History or Branch views?

**Comment by AlexJitianu** [comment]
Thank you helping and for the good news! I've added a new issue for the 2.5.2 release: #129
