### ISSUE TITLE
Show latest commit date and author for each branch in Git Branch Manager

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-git-plugin#138]
This way a user can see which branches are maintained and which are not.

**Comment by sorincarbunaru** [comment]
See `com.oxygenxml.git.view.branches.BranchManagementPanel`.

**Comment by sorincarbunaru** [comment]
What the user asked for:

> I just opened a product repo I hadn’t pulled in several months, and I was trying to figure out which branches the writers had maintained most recently.
> When using the Branch Manager, I often wished it was more of a tree grid, so I could see the latest commit date and author on each branch. The next best thing would be a hover hint on each branch that would show the same info from either a local or remote branch/tag.

**Comment by kirkilj** [comment]
👍🏼
