### ISSUE TITLE
Provide more actionable guidance when pull fails due to an uncommitted conflicting file

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-git-plugin#142]
When both of the following are true:

- A writer has **uncommitted** changes in a file
- An unpulled upstream commit modifies that same file

the plugin shows the following dialog box when a **Pull (rebase)** is attempted:

![image](https://user-images.githubusercontent.com/50950969/129895424-86bbe886-83c8-4f1f-a712-d3c15faabfbe.png)

and the following text when a **Pull (merge)** is attempted:

![image](https://user-images.githubusercontent.com/50950969/129895897-0ce1532f-72a9-4071-b07d-e18c602f2041.png)

This occurs because conflict resolution can only work with _committed_ changes, but the user has _uncommitted_ changes. This can be resolved by committing the indicated files, then reattempting the pull. However, the current message text does not make this clear enough to novice writers. (In fact, it confused me at first until I realized what was going on.)

This enhancement issue requests more actionable text that guides a novice writer to understand what to do next. Maybe this or something similar?

> Cannot pull (rebase/merge) until the following locally modified files are committed or discarded so that incoming remote changes can be applied:

**Comment by sorincarbunaru** [comment]
We'll give this some thought and we'll update this thread when the message is improve.

Cheers!

**Comment by sorincarbunaru** [comment]
The message is now like this:

![image](https://user-images.githubusercontent.com/10512384/132862402-e0e87c29-d7c8-45e2-a9cb-8e8920dbbb38.png)

**Comment by chrispy-snps** [comment]
Thanks @sorincarbunaru, this is great! Do the merge and rebase messages both use this wording (aside from within the parentheses)?

**Comment by sorincarbunaru** [comment]
Yes, Chris! The changes are not made public yet. We plan to make a new release at the end of this month or the beginning of the next one.
