### ISSUE TITLE
Add a tooltip to more clearly describe what each action does in the context menu of a file affected by a commit.

### ISSUE THREAD

**Issue by AlexSmarandache15** [oxygenxml/oxygen-git-plugin#146]
![image](https://user-images.githubusercontent.com/68815668/130433442-30ff6659-c445-4a70-b6fe-b045ba002547.png)
For example, we can add a tooltip for the "Checkout" action to clarify that it reverts the file to the selected version.

**Comment by raducoravu** [comment]
Right, for me as a seldom Git user "Checkout" does not mean anything, I would at least want to have a tooltip which explains what it does like "Revert the contents of the file in the working copy to the current commit".

**Comment by sorincarbunaru** [comment]
@raducoravu, should we add tooltips for all actions, or only for those which may seem a bit unclear to users with less experience with Git?

@FlorinAvram, what do you think?
