### ISSUE TITLE
Issue a friendlier error if the Git server is not accessible

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-git-plugin#151]
When we work remotely, we access our company intranet via our company's VPN server.

Currently, if we forget to connect to the VPN server, the Git plugin issues the following error message when a pull is attempted:

> org.eclipse.jgit.api.errors.TransportException:
> https://my.git.repo.URL/my-repo: cannot open git-receive-pack

This message is confusing to most users, and it does not imply that the problem is connectivity/VPN-related.

Perhaps this message could be replaced with something friendlier, such as

> Cannot connect to the Git repository at
> https://my.git.repo.URL/my-repo

which would more readily imply to our users that the issue is connectivity/VPN-related.

**Comment by sorincarbunaru** [comment]
Hi Chris!

We have noticed this error a few months ago and should be fixed for the next version. 

The new message is "_Unable to access remote repository at: URL_HERE_".
