### ISSUE TITLE
Login dialog with incorrect size on Windows after the git access token expires

### ISSUE THREAD

**Issue by AlexSmarandache15** [oxygenxml/oxygen-git-plugin#152]
My access token has expired and this dialog has appeared:

![image](https://user-images.githubusercontent.com/68815668/133760874-4104529a-9219-4c79-a071-853461c66d86.png)

What is strange is that sometimes after I close it, 2 dialogs appear: this one again and another one, which looks the same dialog but with the correct size and with the selection on the access token authentication(the first dialog has the selection on basic authentication):

![image](https://user-images.githubusercontent.com/68815668/133761072-a2d27c9e-ca9d-4938-9fac-76e696a7c01e.png)

**Comment by AlexSmarandache15** [comment]
The size of the second dialog should also be adjusted because the second label above is not completely visible.

**Comment by raducoravu** [comment]
I think that there are different parts of code which sometimes call on separate threads the Git libraries and trigger the authentication.

**Comment by sorincarbunaru** [comment]
Is this happening if you set the scaling to 100% in Windows?

**Comment by AlexSmarandache15** [comment]
I had 125% scaling.

On 100% scaling, it seems that only this dialog appears, which is ok:
![image](https://user-images.githubusercontent.com/68815668/133770913-53c9ed8f-7c4c-4063-8d27-760ce951f534.png)

**Comment by AlexSmarandache15** [comment]
After removing the preferred size, it seems to calculate its optimal size on its own and now it is displayed correctly on all scaling factors.
