### ISSUE TITLE
Diffing on submodule files failes

### ISSUE THREAD

**Issue by tofi86** [oxygenxml/Oxygen-Git-Plugin#19]
When working with submodules, you often have changes in the submodule git files when you commit something in the submodule.

Diffing those files results in an error in the oXygen Diff (cannot open/read the file).

In those cases you should considder diffing the `.git` file in the submodule directory instead.

**Comment by BeniaminSavu** [comment]
We haven't worked with the git submodules and we will have to investigate a little bit about them. We'll see what we can do.

Thank you for all your feedback

**Comment by tofi86** [comment]
You're welcome! No hurries! :)

**Comment by BeniaminSavu** [comment]
We added some functionality for the git submodules (Sorry for the long delay).  Please let us know what do you think about this feature and what other things would be nice to have.

**Comment by tofi86** [comment]
Works great!

However, when changing to a submodule, there's no way to get back to the original Repository or to swith to another submodule of the parent repo because the icon is greyed out.

**Comment by BeniaminSavu** [comment]
The original repository is in the working copy list, and when you click on the submodules button it should present all the submodules for that parent. If you want to switch to another submodule you have to go back to the original repository.

**Comment by tofi86** [comment]
Indeed, that works, thanks!
