### ISSUE TITLE
Implement i18n fallback to english

### ISSUE THREAD

**Issue by tofi86** [oxygenxml/Oxygen-Git-Plugin#26]
Currently, when a (new) string is not translated (like the ones with 1.0.8 version) the user just sees "de_DE_translation" instead of a proper label.

<img width="432" alt="bildschirmfoto 2017-08-22 um 23 09 04" src="https://user-images.githubusercontent.com/365118/29587661-ec304c42-878e-11e7-83ad-71b0ee513e29.png">

From other Java projects I'm used that there is a fallback mechanism to the default/english language tag. Any chance to implement this?

**Comment by tofi86** [comment]
<img width="361" alt="bildschirmfoto 2017-08-22 um 23 13 19" src="https://user-images.githubusercontent.com/365118/29588829-39db5744-8793-11e7-8ff2-33e54711a19c.png">

**Comment by raducoravu** [comment]
We should probably remove from the "translation.xml"'s header the list of currently not supported languages:

        <language description="French" lang="fr_FR" />
        <language description="Japanese" lang="ja_JP" />
        <language description="Dutch" lang="nl_NL" />

Plus remove the equivalent <val> translation elements for each of those.
This will make the translation fall back to English if Oxygen is started with the user interface in one of these three languages.
For German whenever we add a new key we should place the English translation also as an initial value for the German translation. And @tofi86 or somebody else can translate these later.
