### ISSUE TITLE
Maybe add some contextual menu items in the project view

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/Oxygen-Git-Plugin#28]
For example for a file add an action to commit it or to show it in the Git View.
The API to add contextual menu actions to the project will be available in Oxygen 19.1. See more details here:
https://github.com/oxygenxml/docbook-validate-check-completeness/issues/14

**Comment by AlexJitianu** [comment]
A Diff action as well.

**Comment by raducoravu** [comment]
Ideally when an issue is fixed we would have a link to a commit and some details about what was actually done, what actions have been mounted. In this way the QA team can try and work with the new actions.
