### ISSUE TITLE
Error starting oXygen after install of plugin

### ISSUE THREAD

**Issue by wenamun** [oxygenxml/Oxygen-Git-Plugin#29]
after installing the plugin I get this error message box when I try to start Oxygen (version 17.1 MacOs)

![screen shot 2017-08-27 at 15 22 07](https://user-images.githubusercontent.com/5639069/29750178-94a40b84-8b3b-11e7-8fe8-00918d92ec72.png)

I can close the dialog and oXygen seems to work properly, I can open the Git Staging window/tab, but it is grey and empty.

**Comment by AlexJitianu** [comment]
Hello,

**Comment by AlexJitianu** [comment]
Hi,
Unfortunately, the plugin uses an API that was introduced in Oxygen version 18.1. Making it work for version 17.1 would require implementing in the plugin's code a structure similar to the PluginResourceBundle. Until we get the time to do this, I will mark the plugin as being compatible with version 18.1+ so others don't stumble into this problem.

**Comment by wenamun** [comment]
thanks for clarifying this!
