### ISSUE TITLE
Checking fingerprint on every startup

### ISSUE THREAD

**Issue by tofi86** [oxygenxml/Oxygen-Git-Plugin#38]
> The authenticity of host '...' can't be established.
> RSA key fingerprint ...
> Are you sure you want to continue connecting?

This message is shown on **every** oXygen startup. Why doesn't it cache my choice "Yes"?

Why is it shown anyway? The fingerprint is okay, Sourcetree isn't asking for it everytime?

**Comment by tofi86** [comment]
By the way: after choosing "yes", the plugin says "Cannot reach host" (see #34).

**Comment by AlexJitianu** [comment]
Hi Tobias,

I've created a new build 1.2.3 in which I hope I've solved this issue. Please update the plugin and let me know if I'm right or wrong.

**Comment by tofi86** [comment]
Seems to work now. I was confused by the first time, but sure, it needs to be displayed one time and then cache the "yes" choice. And that works now.

**Comment by AlexJitianu** [comment]
How about the "Cannot reach host"? Do you still get it?

**Comment by tofi86** [comment]
Nope, it's also gone!
