### ISSUE TITLE
Polish the used button icons

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/Oxygen-Git-Plugin#4]
Use only icons designed by us.
For the push and pull buttons position the figures to be on the arrow stem instead of being on the right bottom part like now.

**Comment by AlexJitianu** [comment]
We should also handle the Retina resolutions and dark themes in Oxygen.  To do this we should:
1. use ro.sync.ui.Icons.getIcon(String) to load the images
2. for each icon we should have variants for retina/dark using this naming convention:
https://www.oxygenxml.com/doc/versions/19.0/ug-editor/topics/using-retina-hidpi-images.html#using-retina-hidpi-images__retina-naming-convention-section
