### ISSUE TITLE
Branch management

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-plugin#42]
Currently you can only switch between local branches. We should also present the remote branches and allow the user to check out these remote branches. Maybe more? Perhaps others can tell us what branch-related functionality they find useful and use relatively often.

**Comment by raducoravu** [comment]
+ 1:
https://www.oxygenxml.com/forum/post44586.html#p44586

**Comment by AlexJitianu** [comment]
The plugin also has an action to clone a repository. It is useful to allow the user to select which branch they checkout by default. Having this might save the user from further headaches. For example you commit accidentally on the wrong branch and you then have to move the commit on the correct branch.

**Comment by xephon2** [comment]
any progress here?

**Comment by AlexJitianu** [comment]
Well, we did the easy part, the branch selection when cloning a repository. The branch management is next on our road map. We were thinking to enhance the current branch management dialog to something like this:
![branch management](https://user-images.githubusercontent.com/7802649/42570044-4489e0bc-851b-11e8-92b4-ca7a2fa1c9cd.png)

**Comment by codemaestro** [comment]
Sounds like this issue has gone about as far as it can in two years. Users can now create branches from existing commits in the branch history. For some reason selecting remote branches is still not there.

I find the git client rather slow when switching between branches as well. I'm not sure how to speed up the screen display after loading a new local branch.

**Comment by sorincarbunaru** [comment]
Hello,

A better branch management is a priority for us right now, and we plan to have it sometime this summer. We plan to start working on this in a couple of weeks or so.

Regarding the speed of changing the local branch, I suspect it has something to do with some UI updates, but we will need to take a deeper look at this. I created a new internal issue for this (it's easier for us to manage the life cycle of the issue this way), and we will update this thread when we release a version that improves the branch switch speed.

**Comment by sorincarbunaru** [comment]
We created a new side-view called _Git Branch Manager_, where all the local and remote branches are shown. You can checkout remote branches, and you can also checkout, create or delete local branches. See issues #102, #103, #104. We now have someone looking at #108.

Having said all these, I think I can close this issue right here. We already have or will add particular issues for particular actions or improvements.
