### ISSUE TITLE
History view

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-plugin#43]
For a branch or current branch, present the commits, their message, what resources change (with the possibility of a diff)  etc.

**Comment by AlexJitianu** [comment]
A proposal about how such a view could look like.
![git_history](https://user-images.githubusercontent.com/7802649/63941621-aaad1e00-ca74-11e9-9484-ee224a2b0868.png)

**Comment by AlexJitianu** [comment]
1. We can start by creating the table view/model for presenting the commits. We can present all the commits from the current branch or only the commits related with a specific file.
2. The graph representation about how revisions were merged. A decorator capable of drawing the lines/points for a commit.
3. Information about the commit selected in the table.
4. The resources contained/changed in the commit. We can use the same view from the unstaged/staged views of the plugin.

https://stackoverflow.com/questions/15822544/jgit-how-to-get-all-commits-of-a-branch-without-changes-to-the-working-direct
https://github.com/centic9/jgit-cookbook/tree/master/src/main/java/org/dstadler/jgit/api

**Comment by sorincarbunaru** [comment]
Implemented in version 2.0.0. There is a **Show current branch history** action in the Git Staging side-view, and a **Show in history** action in the contextual menu of each unstaged resource.
