### ISSUE TITLE
Flat view - make the file name fore visible

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-plugin#52]
The fileas a represented like this: 
`file_name - file_path`
I would gray out the path so that the file name is more visible.

**Comment by AlexJitianu** [comment]
I think its better to have two columns: "File name' and "Path'. Having the file names in a column would make them more visible and easy to focus on.

**Comment by sorincarbunaru** [comment]
We now present the changed files like this: path/to/the/file.ext. Users have not complained until now. Closing this issue.
