### ISSUE TITLE
Slow performance when trying to stage selected

### ISSUE THREAD

**Issue by shudson310** [oxygenxml/oxygen-git-plugin#53]
The plugin is very slow to update the list of files, especially when trying to stage individual selected files. We've seen this on both Windows and Mac.

**Comment by AlexJitianu** [comment]
Hello,

Thank you for reporting this issue. I reproduce it myself when I have may  changes by selecting and staging a lot of them or, even worse, by clicking Stage All. I will posta notification here when we release a new build that contains the fix.

**Comment by AlexJitianu** [comment]
A new build is available that should fix the performance issue. You can update to it by going to Help->Check for add-ons updates... and by following the update procedure. Please let me know how it goes.
