### ISSUE TITLE
Need a way to reset authentication

### ISSUE THREAD

**Issue by shudson310** [oxygenxml/oxygen-git-plugin#54]
When our Bitbucket password changes, there doesn't seem to be a way to change the username/password that is used by the plugin.

**Comment by AlexJitianu** [comment]
Hello,

The first time the plugin detects that the credentials are invalid it will ask the user for the new ones. This usually happens on Pull/Push actions. Is the plugin behaving differently in your case?

**Comment by AlexJitianu** [comment]
We could put such an action in either a global menu or in an options page. An action on the toolbar would open that options page.

**Comment by AlexJitianu** [comment]
Hello,

We've identified an issue in the code that sends the credentials to the server. If the credentials are rejected by the server, the engine actually retries 3 times with the same credentials before requesting new credentials from the user. We fixed this behavior in the latest plugin build 1.3.0 so, even if though we don't have a manual reset yet, I expect it to work better for you now.

**Comment by shudson310** [comment]
The plugin is working much better now, though when oXygen restarts, you have to re-input your credentials. I'd prefer some kind of settings dialog, where you could store your username and password and reset the password if needed.

**Comment by AlexJitianu** [comment]
Hello,

After you are asked for username/password, the plugin stores them and you will never be asked for them again (assuming they remain valid). If I understand correctly, every time you restart Oxygen you are asked for credentials although they didn't change on the server? If that's the case, after you restart Oxygen, can you make a screenshot with the dialog? 

Thank you,
Alex

**Comment by sermo-de-arboribus** [comment]
We have a team of >10 people collaborating in a project that uses the Git Plugin (version 1.5.2 in oXygen 21.1). We have noticed severe authentication issues after a password change, as suggested in this thread here. Although provably entering correct login data, they have been refused two to three times with a message that authentication failed; only the third or fourth login attempt succeeded. Many users were inclinced to give up rather than keep trying again and again. The transport method used for connecting to the remote repo is HTTPS. Any ideas how we could facilitate the resetting of authentication without the need to enter the same login data many times in a row?

**Comment by sorincarbunaru** [comment]
Hello,

Thank you for the feedback! For a better issue life cycle management, we also have an internal issue recorded for creating an easy way for resetting the credentials, and I added your vote.

Unfortunately, for now, the single option is to edit the preferences file by hand. For oXygen XML Editor, the preferences folder is found at the following locations:
 - Windows (Vista, 7, 8, 10) - [user_home_directory]\AppData\Roaming\com.oxygenxml
 - Windows XP - [user_home_directory]\Application Data\com.oxygenxml
 - Mac OS X - [user_home_directory]/Library/Preferences/com.oxygenxml
 - Linux/Unix - [user_home_directory]/.com.oxygenxml

You need to open "oxyOptionsSa21.1.xml" and delete the "userCredentials" element...

In the future we will try to create an easier way from the UI, in the Preferences dialog. If you have any other suggestions, feel free to tell us :).

**Comment by sermo-de-arboribus** [comment]
Ha, you're still coping with people who use Windows in XP (in 2019!) :grin:

Thank your for this info, that's very helpful for supporting our team in case of login problems!

**Comment by sorincarbunaru** [comment]
Hello! Just wanted to let you know that the newest version of the add-on (2.2.0) comes with a **Reset all credentials** action in the menu presented by the Settings button from the main toolbar 😄 .

**Comment by shudson310** [comment]
thank you!! This will be a helpful feature!

--Scott
