### ISSUE TITLE
Clone Repository window accepts no input, cannot be closed

### ISSUE THREAD

**Issue by larkvi** [oxygenxml/oxygen-git-plugin#58]
On 19.1, build 2017121318. Update feature says this is current latest version. Machine is running a recently-installed copy of Windows 10 Enterprise.

Freshly installed oxygen-git-plugin according to instructions, started new project, opened an xml file in the project. When I click on the '+' sign to clone the repository, window opens up, as expected:

![oxygen_git_window](https://user-images.githubusercontent.com/12297045/36672723-a1a0712e-1b00-11e8-94d2-e6823b39939f.PNG)

This window accepts no input in the text field. Neither 'OK' nor 'Cancel' can be selected. The 'X' to close the window can be highlighted, but clicking it yields no results. Window cannot be exited, and program must be forced to quit using the Task Manager.

**Comment by AlexJitianu** [comment]
Thank you for reporting this issue. We made a new build (1.2.8) in which we fixed this behavior. You can update by invoing the action **Help->Check for add-ons updates...**. 

After updating, if you don't see this problem anymore, please let me know so that I can close this issue.

**Comment by larkvi** [comment]
I installed an update and everything now works as expected. Cheers.
