### ISSUE TITLE
Can't access branch

### ISSUE THREAD

**Issue by caedmon5** [oxygenxml/oxygen-git-plugin#59]
We have a project that has a master and a development branch. I'm the administrator (in case permissions are the issue). 

In Oxygen, I simply cannot access the development branch. When I click on the branch icon in git staging, I get the right dialogue box, but it only has one option: the master.

This is for a private repository. Weirdly, it seems to write to Master even when I have branch protections on, including applying them to administrators.

**Comment by AlexJitianu** [comment]
Hello,

Currently the plugin allows switching only between local branches. That's probably why you don't see any other branches. Checking out remote branches is on our short term TODO list so I will add your vote the feature.
Until this support is available, you cen use an external Git client to check out the remote branches. Afterwards, you will be able to switch between them directly from Oxygen.

**Comment by esc** [comment]
We have multiple local branches, but somehow the plugin doesn't see any except master. I think there is a bug in the code.

**Comment by sorincarbunaru** [comment]
Hello @esc,

I have just teste with oXygen Author 20.1 and Git Staging plug-in 1.3.2, and I can switch between local branches... 

![image](https://user-images.githubusercontent.com/10512384/47408284-63c10e80-d767-11e8-9685-ce93e23084c5.png)

In order to have the local branches visible, you have to create them using some other Git clients, as our plug-in is not yet able to do that. By the way, can you see these local branches and switch between them using other Git clients?

**Comment by kirkilj** [comment]
I was in the middle of a training session and discovered the same thing about not seeing remote branches. I had the class use TortoiseGit to look on the remote for a list of branches they could pull down. So yeah, there's a workaround if you know how, but it still was a diversion for them. 

Note to self: try an operation on a sample student environment before you do it in a class. ;)

**Comment by sorincarbunaru** [comment]
So this happened on an another PC than the one you are normally using, right? Were you able in the end to use the add-on?

**Comment by sorincarbunaru** [comment]
We recently replaced the branch selection dialog with a side-view called _Git Branch Manager_. Therefore I will close this issue, and if any problems arise with the Git Branch Manager, perhaps a new issue should be opened. By the way, the new version of the add-on will probably be available at the end of this month or the beginning of the next one :).
