### ISSUE TITLE
Is pull --rebase supported somehow?

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#65]
Our workflow is to use `git pull --rebase`. Does the plugin just do a standard pull? Is there a workaround besides using the command line for that? I created an External Tool for that purpose as a test, but I wanted to see if we could make the plugin a standard part of our Oxygen installs.

**Comment by AlexJitianu** [comment]
Hi,

Currently there isn't a way to activate a --rebase pull. How about if we put this option in a preferences page? A settings button on the view's toolbar will take you to this page? Or would you prefer for the Pull action to always present a dialog with this check box? (among other options)

**Comment by kirkilj** [comment]
In the specific doc group I mentioned, they use rebase in their workflow while others do not, so it would be _preferable_ to put it in a _preference_ page for the plugin. Since we all like to abstract out functionality to create a general solution, if there were a way to specify a set of default git options to each git function present in the plugin's GUI, then the Oxygen admin could specify any custom string that would be append to the standard git function. In the pull example, the admin could specify that "--rebase" be added to the pull function, while other functions could have their own option strings. For my own use, I've made a list of the Git commands I use most frequently and created a set of External Tools for them and use the default value and ask function to present a default and allow the user to override. 

I don't know what freedom the JGit lib provides for passing through a Git option string, so I don't know if you can easily do the same in the Oxygen plugin somehow. Perhaps you could have a button in the plugin's toolbar to allow similarly configurable custom Git commands.

![image](https://user-images.githubusercontent.com/128799/44007653-063bd1f0-9e5f-11e8-9da5-9e3655d896b8.png)

**Comment by AlexJitianu** [comment]
Hi,

> I don't know what freedom the JGit lib provides for passing through a Git option string,
I haven't found such a feature... You basically have to use JGit's Java API to set any Git options on each commands. So we will have to go with either the preferences page option or the Push dialog that offers extra options.

The next version of Oxygen is scheduled around February so we will probably tackle the plugin related issues 2 months prior to the release, once the major features are near completion.

Best regards,
Alex

**Comment by kirkilj** [comment]
Hi Alex,

Do you know if JGit picks up and uses the standard git config files in the .git directory? That could be another path, I suppose, as long as the desired options can be expressed somehow in a default config setting if it exists.

**Comment by kirkilj** [comment]
Apparently, rebase can be set as the default pull option globally, per repo, or per branch.

`git config --global pull.rebase true` will do it globally for a given local machine, for example.

I have not tested to see if the add-on will honor the setting through JGit, but there's hope.

**Comment by sorincarbunaru** [comment]
The recently released version 2.0.0 now comes with a **Pull (rebase)** action in the menu shown by the Pull toolbar button.
