### ISSUE TITLE
Push via SSH-Protocol broken

### ISSUE THREAD

**Issue by M3ssman** [oxygenxml/oxygen-git-plugin#70]
Hello there,

I'm having trouble with Oxygen-XML on Ubuntu using SSH-Urls. 
The remote repository I'd like to access resides in a self-hosted GitLab-CE-Instance.

The remote url is `git@git.itz.uni-halle.de:aqayv/oxygenxml-sample-ssh.git`, pushing and pulling via usual Bash works fine, but not with Oxygen-XML. The Editor only shows up an error pane message: `org.eclipse.jgit.api.errors.TransportException: git@git.itz.uni-halle.de:aqayv/oxygen-sample-ssh.git: null` 

Using HTTPS instead of SSH doesn't yield any Errors, but it asks for Credentials every time, which is somehow annoying, since I'm using ssh with keys in all other places.

Any help is appreciated!

  

**Platform**
OS: Ubuntu 18.04 LTS
Oxygen-XML: 21.1 build 2019052108, Trial Version

**Comment by M3ssman** [comment]
FYI:

When I switch to the Git Staging Pane (left bottom), there's a warning every time `Host nicht erreichbar`

**Comment by sorincarbunaru** [comment]
Hello Uwe,

Did this happen after updating to version 1.5.0 of the add-on, or did you also notice it before? In version 1.5.0 we changed the default SSH session factory to one based on Apache MINA SSHD. You can switch back to the one based on JSch by adding "-DuseJschForSSHOperations=true" in "oxygen21.1.vmoptions".

All the best wishes,
Sorin Carbunaru
oXygen XML

**Comment by M3ssman** [comment]
@sorincarbunaru 

This is my first attempt to use Oxygen XML with git integration, therefore I can't tell if worked previously. The Plugin Version is 1.5.0.

**Comment by M3ssman** [comment]
It's getting crazy:

if remote URL is prefixed with `ssh://` , explicitly mentioning the protocol, Oxygen XML is able to push to remote origin, at least it assumes it does. 

But at our remote Git-Service (GitLab-CE selfhosted), no Data is received. Local repository clone says everything is fine, so you even don't have a chance to push via Terminal and your commit is lost!

**Comment by sorincarbunaru** [comment]
@M3ssman,

1. Is there any chance for you to test the same scenario on a Windows machine? I tested the Git add-on with a project hosted on the "public" GitLab platform (so not an locally installed Community Edition) on Windows, and I could successfully use it. I would like to see if the OS makes any difference, or perhaps the Git platform...
2. Have you tried adding the Jsch flag I mentioned? If yes, did you notice any improvements?
3. You could also try using the 1.4.0 version of the add-on, before we switched to the new SSH library. Download the JAR from https://github.com/oxygenxml/oxygen-git-plugin/releases/download/1.4.0/git.support-1.4.0-plugin.jar and extract the `git.support-1.4.0` folder into `[OXYGEN_INSTALL_DIR]/plugins`.

As a side note, we chose to change the default SSH library because this Apache MINA-based one supports more kinds of keys, but if it proves to bring other problems, we may have to reconsider. That's why I would be grateful if you could also try version 1.4.0 of the add-on or version 1.5.0 with the `-DuseJschForSSHOperations=true` set.

Best wishes!

**Comment by M3ssman** [comment]
@sorincarbunaru 

1. No, sorry.

2. Using Jsch alone doesn't improve the situation, sorry. The `<oxygen>/output.log`-File has less information about what's going on

```
0 INFO [ pool-1-thread-1 ] org.apache.sshd.common.util.security.bouncycastle.BouncyCastleSecurityProviderRegistrar - getOrCreateProvider(BC) created instance of org.bouncycastle.jce.provider.BouncyCastleProvider
2 INFO [ pool-1-thread-1 ] org.apache.sshd.common.util.security.eddsa.EdDSASecurityProviderRegistrar - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
```

3. **Yes**: Jsch-Flag plus Version 1.4.0 works with our GitLab-CE-Service and an URL like `git@git.itz.uni-halle.de:aqayv/oxygenxml-sample-ssh.git`. 

Only a minor drawback: the arrow (left top) is not marked with an "+1"-sign if the local clone is 1 commit ahead it's remote counterpart (V.1.5.0 included this, I guess?). But besides this, it is usable with the former version and the flag (though, I didn't try the Jsch-Flag alone)

Thanks so far!

**Comment by SchaperC** [comment]
Same issue here, +1.

**Comment by sorincarbunaru** [comment]
Hi @SchaperC,

1. Could you please specify the Git platform and type (GitHub, GitLab, BitBucket, self-hosted or not, etc) and the OS of your machine?
2. Can you confirm that version 1.4.0 (see https://github.com/oxygenxml/oxygen-git-plugin/issues/70#issuecomment-502001453) works fine?

Thank you!

**Comment by sorincarbunaru** [comment]
@M3ssman , @SchaperC 

Could you both please copy [log4j.zip](https://github.com/oxygenxml/oxygen-git-plugin/files/3301418/log4j.zip) to your oXygen installation directory? This would create some log files on your Desktop (look for "oXygenLogs") that you could send back to me for further analysis.

Thank you again!

**Comment by SchaperC** [comment]
@sorincarbunaru

1. GitLab, Ubuntu 19.04
2. version 1.4.0 works fine

**Comment by SchaperC** [comment]
@sorincarbunaru
I have copied the log4j.properties file to my oXygen installation directory. Here is the output for a pull attempt with version 1.5.0:
[oxygen.log](https://github.com/oxygenxml/oxygen-git-plugin/files/3306080/oxygen.log)

**Comment by sorincarbunaru** [comment]
@SchaperC 
Is it gitlab.com, or a self-hosted GitLab instance (something like: gitlab.domain.name)?

**Comment by sorincarbunaru** [comment]
@SchaperC 
Thank you for the log files.

**Comment by SchaperC** [comment]
@sorincarbunaru
self-hosted GitLab, hosted by Humboldt University, Berlin/GER, https://scm.cms.hu-berlin.de (cf. log file)

**Comment by M3ssman** [comment]
@SchaperC 
Where is this log supposed to be? Can't find it. I placed the log4j-Props straight into the local install Folder, in my case `/home/m3ssman/Tools/Oxygen XML Editor 21`.

@sorincarbunaru 
As mentioned, the Error is not shown, when die Repository URL is prefix with `ssh`-Protokoll like this
`ssh://git@git.itz.uni-halle.de:aqayv/oxygenxml-sample-ssh.git` . Unfortunately, our self-hosted GitLab-Service at Martin-Luther-University Halle-Wittenberg doesn't like this URL-Pattern, it can't connect this way. Maybe it helps to please the Oxygen XML SSH-Lib in case of missing Protocol to add the `ssh://`- Prefix only for internal use?

**Comment by sorincarbunaru** [comment]
1. It seems you placed the `log4j.properties` file in the right place. It should be on the same level with the oXygen launcher. The log files should be on your Desktop. Look for `oXygenLogs`.
2. We will have to perform some more tests on our site, I guess, so we'll need a little more time. Until now I didn't manage to get the same Java exception that @SchaperC  got. I tried with a Ubuntu 18.10 VM and a self-hosted GitLab instance. I only loose the connection from time to time, but when I try to push or pull, it seems the Git client wakes up. Well, what can I say?... Sometimes you wish your app to crash in a certain way, and it doesn't. Lucky me!

**Comment by M3ssman** [comment]
@sorincarbunaru 
Gosh! I'm so stupid sometimes, I can't believe myself ... since I have german Ubuntu Desktop Installation, I found nothing is copied to the Desktop since it is called `Schreibtisch` . Anyway, the Property-File creates indeed a file at `${user.home}/Desktop/oxygenLog/oxygen.log`. ;)
[oxygen.log](https://github.com/oxygenxml/oxygen-git-plugin/files/3314284/oxygen.log)

**Comment by sorincarbunaru** [comment]
_Danke_ for the log file, @M3ssman! :)

**Comment by sorincarbunaru** [comment]
Hello again @M3ssman, @SchaperC,

Could you please add the following line to the "log4j.properties" file?

`log4j.category.com.oxygenxml.git.auth.ResolvingProxyDataFactory=debug`

Then please uninstall the current Git add-on, install the one from http://www.oxygenxml.com/userFiles/git.support-1.0.0.zip by unzipping it to [oXygen_install_directory]/plugins, regenerate the logging and post it here. Please also let me know if you notice any improvements with this build of the Git plug-in.

Thank you so much for your help!

**Comment by SchaperC** [comment]
@sorincarbunaru
No improvements yet.
[oxygen.log](https://github.com/oxygenxml/oxygen-git-plugin/files/3324605/oxygen.log)

**Comment by M3ssman** [comment]
@sorincarbunaru 
Guess what? Works fine!

Sorry, the logfile contains new and previous entries(from our first try, see above), so please take a look at the end. Extended the logging conversion pattern to include timestamp, but this took place only in the very latest run.

[oxygen.log](https://github.com/oxygenxml/oxygen-git-plugin/files/3333514/oxygen.log)

**Comment by sorincarbunaru** [comment]
@SchaperC, can you please also tell me the following:
1. The key type (RSA, DSA, ECDSA, etc).
2. Where the keys are stored. They should probably be in `~/.ssh`.

@M3ssman, please do the same thing. I would be interested in comparing the key types and locations that you use, given the fact that for you that test build worked fine, but not for @SchaperC .

Thank you for your help!

**Comment by SchaperC** [comment]
@sorincarbunaru
1. RSA
2. $HOME/.ssh

(as it also says in the log file, if I am not mistaken)

**Comment by sorincarbunaru** [comment]
@SchaperC, could you please try the plug-in from http://www.oxygenxml.com/userFiles/1423190703025822.zip? From the log file we noticed that your private key is password protected, and this didn't work with version 5.3 of the JGit library, therefore we updated the library, and after also fixing something in our code, the authentication started working for us. Please let me know how it works for you.

@M3ssman If it wouldn't too much of a pain, could you also try this private build of the add-on?

**Comment by SchaperC** [comment]
@sorincarbunaru
This version works fine!
Thanks for developing oxygen-git-plugin.

**Comment by sorincarbunaru** [comment]
Pfew... I am so glad it works. I hope we will manage to fix a few more issues and release a new public version of the plug-in by Monday... Thank you for you patience and your help!

**Comment by AlexJitianu** [comment]
We've just relased a new version of the plugin 1.5.1 that contains all of these fixes. I will close this issue and consider it done.
