### ISSUE TITLE
Add support for Git Blame

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#71]
The GitLens addon for Visual Studio Code can show either the last person who added/changed the current line or selection of code or show all commits that touched the given line/selection. I'm assuming it's using Git Blame. These could appear in a dialog box upon a right-click action or by using buttons perhaps in a new Git History View.

![image](https://user-images.githubusercontent.com/128799/64042831-65e2bf00-cb28-11e9-93be-6da779b7ab38.png)

**Comment by sorincarbunaru** [comment]
Version 2.0.0 of the add-on has just been released and it comes with a "Show blame" action for the unstaged resources.
