### ISSUE TITLE
Is there any way to install this plugin in offline mode

### ISSUE THREAD

**Issue by liuxiaopiao** [oxygenxml/oxygen-git-plugin#72]
Is there any way to install this plugin in offline mode? 
We have no internet network access when using Oxygen XML editor, so would like to install this plugin in offline mode. 

Could you please give me a hand on the detailed steps? Thanks a lot.

**Comment by AlexJitianu** [comment]
Hi,
All you need to do is unzip the release jar file into {oXygenInstallDir}/plugins:
https://github.com/oxygenxml/oxygen-git-plugin/releases/download/1.5.2/git.support-1.5.2-plugin.jar
Just make sure you don't create any intermediate folders. After unzip, the file system should be like this: {oXygenInstallDir}/plugins/git.support-1.5.2/plugin.xml
I will add a section describing this procedure to the readme file.
