### ISSUE TITLE
Add a "Committing" progress indicator message in the status bar with commit button.

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#74]
The other operations like Push and Pull have such a message. It can take several seconds for a commit to complete and it's confusing for users sometimes, since they dependent on the other progress messages to tell them that an operation is underway.

**Comment by sorincarbunaru** [comment]
Hello John,

We already had an internal issue recorded for this, but we didn't find the time for it yet. I added your vote to it.

By the way, we would be more than glad to accept any pull request if you or a colleague of yours would be willing to contribute to the add-on 😄 .

Best wishes,
Sorin C.

**Comment by sorincarbunaru** [comment]
We added a "_Committing..._"message as well as a busy cursor, when needed. The next minor release will come with this minor improvement.

**Comment by sorincarbunaru** [comment]
Version 2.1.0 is available now :).
