### ISSUE TITLE
Provide an option for commit --amend

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#75]

**Comment by sorincarbunaru** [comment]
Added you vote for this to our internal issue (it's easier for us to manage the JIRA issues than the GitHub ones, going through a well established internal workflow).

**Comment by kirkilj** [comment]
By the way, I am glad to see that the pull rebase and git history/blame features have been added. Even though the submodule support was there in prior versions, it is now critical for us since we're using them for content reuse across repos. Great job all around! Thank you.

**Comment by sorincarbunaru** [comment]
Thank you for your words of appreciation! 😄

**Comment by sorincarbunaru** [comment]
Hello!

Just wanted to let you know that in the recently released version of the Git Client (2.2.0) we added the possibility to amend the last commit 😄.

Best wishes!
