### ISSUE TITLE
Commit doesn't work in some repos

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#81]
I've had 3 instances where I received the commit successful message, but the changes listed in the stage did not clear out. I've had it when the changes that were staged were file deletions only, but it happened just now with only modifications. Doing a git status or git log from the command line or other Git tool verified that the commit did not occur. The changes are still staged. 

https://imgur.com/VIyyqgq 

$ git status
On branch 19.FP2
Your branch is up to date with 'origin/19.FP2'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    content/_sample.ditamap
        deleted:    content/_sample_content_dir/README
        deleted:    content/_sample_content_dir/_sample_topic.dita

**Comment by sorincarbunaru** [comment]
Hi John,

Did this happen with multiple repositories?

**Comment by sorincarbunaru** [comment]
Inside the attached archive there is a logging configuration file. Copy it inside oXygen's installation folder, and after reproducing the problem, add the "oxygenLogs" folder form your Desktop to an archive and send it to us at support@oxygenxml.com.

By they way, I suppose you have the latest version of the Git add-on (2.1.1) installed, right? Version 2.1.0 should be as good...

[log4j.zip](https://github.com/oxygenxml/oxygen-git-plugin/files/4491652/log4j.zip)

**Comment by AlexJitianu** [comment]
Hi John,

Looking inside the code, I see that whenever the commit fails, an exception is printed in the console, but no information is presented to the user. I will fix that for the next release. The user will see a dialog informing him that the commit failed, as well as why it failed.

**Comment by sorincarbunaru** [comment]
We now show the commit failure messages in version 2.2.0.

**Comment by AlexJitianu** [comment]
I think the strange behavior was related with the commit errors not being presented. John, if you still experience strange behavior, we can reopen this. With the new version you should receive more details about why the commit fails and that can help us track the cause.
