### ISSUE TITLE
Editor variables for current Git repo and branch

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#82]
We could perform some more integration between Oxygen and our environment if there were Oxygen editor variables for this plugin. The immediate ones we could use are currentGitRepo and currentGitBranch.

**Comment by sorincarbunaru** [comment]
Hi John,

I just created an improvement request in our company's issue management system. It's easier for us to manage the life-cycle of an issue there. We will update this thread when the improvement is done. 

By the way, the issue ID is EXM-45428 (for reference purposes).

**Comment by kirkilj** [comment]
Thanks

**Comment by kirkilj** [comment]
Hi Sorin, will these custom editor variables make it into an upcoming update?

**Comment by sorincarbunaru** [comment]
Hi John,

We will try to push them in the next release (in 2 weeks or so, I would say). 

Two questions:
1. current Git repo - do you want it to be the URL to the remote repo, the path to the local working copy, or the path to the .git folder of the current working copy?
2. current branch - I suppose it would be best for it to provide the full name of the branch, right? E.g. "refs/heads/master".

**Comment by sorincarbunaru** [comment]
Note for @bogdandr14: @AlexJitianu  suggests using ro.sync.exml.workspace.api.util.UtilAccess.addCustomEditorVariablesResolver(EditorVariablesResolver).

**Comment by kirkilj** [comment]
Hi Sorin,

In my use cases, I was only interested in the names and not the remote or local paths. However, I can imagine that the paths could be useful in some circumstances. Rather than provide multiple variables, would it be possible to provide a parameter to indicate what type of info to return about the repo or branch?

John

**Comment by sorincarbunaru** [comment]
Umm... I think we could do something... But why do you prefer a parameter? I would say that ${gitBranchShortName} and ${gitBranchFullName} is vey similar to writing ${gitBranchName(short)} and ${gitBranchName(full)}, or something like that. Did you have some other way of writing this in your mind?

**Comment by kirkilj** [comment]
The only reason would be if you wanted to be able to provide several other data items besides just short and long names in the future, as well as local vs remote scope, as well as the ability to store the result in a @variable like the ${ask} function. It might be useful to also think about what collections might be useful to return so the can be iterated over. For example, return a list of all submodules in a given repo/branch.

Basically, I wanted to explore if it would be best to think about expanding the variety of data that can be returned from the plugin at the outset before hard-working 3 or 4 specific variables. 

Here is a separate, yet related, issue: The menu of variables in the ellipsis button is getting so long that it can take several clicks on the "more" menu item to traverse all of them, especially if there are several custom editor variables being maintained on a project level as well. I think a dialog box with a filter for name or type of variable would be a more usable interface, like you do in several other places in Oxygen, such as content completion, reusable components, preferences, etc.

**Comment by sorincarbunaru** [comment]
I was "afraid" you were going to ask for more 😆. But I do understand what you say, and I agree.

So... I guess we could have a `${git(param)}` variable, where `param` could be: `short_branch_name`, `full_branch_name`, `local_repo_name`, `local_repo_path`, and so on. In the beginning we will probably only have these 4 that you have specifically requested.

Do we have a deal? 😄 

In regards to the last paragraph, it sounds good to me. I added a new issue for Oxygen (EXM-46365).
