### ISSUE TITLE
Add pre and post hooks to the functionality in the add-on

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#85]
If we could create pre and post listeners in Java, or better yet JavaScript, through a Git-Staging SDK for the add-on's events, we could do a much better job of integrating our workflows into Oxygen rather than forcing the user too take many side trips to the command line or other Git tools to run git commands or custom shell scripts. Even if our devs need to write shell scripts, they could be invoked from the executeCommand APIs, and the results of the hook action could be interpreted by the invoking JavaScript.

Sometimes, the desired actions can be done solely through Git's own hooks, depending on the use case.

**Comment by AlexJitianu** [comment]
The plugin already contains a [com.oxygenxml.git.service.GitEventListener](com.oxygenxml.git.service.GitEventListener) which could be leveraged. First, you would need to fork this project and intervene in its entry point [com.oxygenxml.git.OxygenGitPluginExtension.applicationStarted()](https://github.com/oxygenxml/oxygen-git-plugin/blob/master/src/main/java/com/oxygenxml/git/OxygenGitPluginExtension.java) and add such a listener.

**Comment by AlexJitianu** [comment]
For now, one can rely on Git hooks to implement such functionality. The project can also be forked if needed.
