### ISSUE TITLE
Great update! Minor glitch in README link in Oxygen.

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#86]
What a great update to a great plugin! Thanks for taking the time to enable these features. They will make it easier for our writers to adopt it for most of their git operations.

Minor glitch: When I click on the link in the add-on's release notes dialog in Oxygen:

> For more information about the add-on's features, see the README document.

The link actually has an href of 

> https://github.com/oxygenxml/oxygen-git-plugin/blob/master/README.md.
with the period after "md" being part of the link, which results in a 404. Taking off the period fixes it.

**Comment by sorincarbunaru** [comment]
Hi John!

Thank you for your words of appreciation! We hope our users will be happy with the new release.

Thank you for reporting the glitch too! It should now be fixed (it seems to require an Oxygen restart, though).
