### ISSUE TITLE
Old build (1.0.0) is committed to the repository

### ISSUE THREAD

**Issue by georgebina** [oxygenxml/oxygen-git-plugin#89]
https://github.com/oxygenxml/oxygen-git-plugin/tree/master/build
contains `git.support-1.0.0-plugin.jar` from 3 years ago.

This is not referred by addon.xml, which points to the releases now. I think we should remove this from the repository.

**Comment by AlexJitianu** [comment]
The update site refers builds directly from the Release section. This might have been an initial build that we forgot about. I removed it.
