### ISSUE TITLE
Refresh state of entire view when activated

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/Oxygen-Git-Plugin#9]
For example if I make changes in Source Tree and then switch to Oxygen the entire Git view should refresh. Right now the "Unstaged" resources seems to refresh. But the list of already staged resources or the counters on the buttons used to Push or Pull resources seem to remain with stale info.

**Comment by raducoravu** [comment]
Maybe also some kind of manual refresh button or listen for the F5 shortcut to refresh and reload the new information from the local repository.

**Comment by AlexJitianu** [comment]
Currently the refresh events are scheduled on focusLost/focusGain in the view. Maybe we should also detect the transitions windowDeactivated/windowActivated on the Oxygen frame and schedule a refresh.
