### ISSUE TITLE
Ask for confirmation when no commit message is present

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-plugin#90]
If the user presses the _Commit_ button and there is no commit message specified, we should ask the user if it really wants to commit like that.
It can be a warning oe question dialog, with O.K(or Commit). and Cancel and a message something like: 

`The commit message is empty. It is recommended to give a description of your changes. Are you sure you want to commit without one?`

We should intervene inside `com.oxygenxml.git.view.CommitAndStatusPanel.CommitAction`.  We can use a method from `ro.sync.exml.workspace.api.WorkspaceUtilities`. These methods don't have a _Never show this again_ feature, but, considering it's not recommended to commit without a message, I think it's O.K. to ask for confirmation every time it happens. Chances are it will give a message.

**Comment by AlexJitianu** [comment]
@bogdandr14,  we should pass those messages through translation.

**Comment by AlexJitianu** [comment]
I tested to see if the message is presented and what it does for each presented option: Commit or Cancel.

**Comment by AlexJitianu** [comment]
Small code review: instead of `commitMessageArea.getText().contentEquals("")` let's use `commitMessageArea.getText().isEmpty()`

Also, let's try with a _Continue_ button and let's put the 'Are you sure' part on a new line.

**Comment by raducoravu** [comment]
Don't we usually use internationalization for all user interface messages?

**Comment by bogdandr14** [comment]
> Don't we usually use internationalization for all user interface messages?

I modified this problem, but forgot to tag the commit.

**Comment by AlexJitianu** [comment]
- The message should be a warning, not a question
- The buttons: _Commit anyway_ si _Cancel_
- Trim the text before testing it: `commitMessageArea.getText().trim().isEmpty()`

**Comment by AlexJitianu** [comment]
Still have to make the message a warning, not a question.

**Comment by sorincarbunaru** [comment]
Code review: instead of `commitButton.transferFocusBackward()` I would try `commitMessageArea.requestFocus()`, because if another component will be inserted between the message area and the button, the focus will be transferred to that new component instead of the message area.
