### ISSUE TITLE
Branch Operations

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#94]
Thanks for adding the "Create branch" option to the commit history. I use it every day. For future inspiration ;), here's the list of commit context menu commands from a Windows Explorer extension we use sometimes. For a GUI trying to support lots of options, the ellipsis can bring up fully featured dialog boxes, but there may be many common use cases that either need a few options, such as (hard, mixed, soft) on the reset command, while some may not require any.

- Merge to <current branch>...
- Reset <current branch> to this... (*)
- Switch/Checkout to this... (*)
- Create New Branch from this... (already in plugin)
- Create tag at this... (*) 
- Rebase <current branch> onto this...
- Revert change by this (*)
- Cherry Pick this... (*)
- Show branches this commit is on (*)

I've put (*) on the items I frequently use.

**Comment by AlexJitianu** [comment]
Thank you for your hints! I've added your feed back on our internal branch support issue. We will go over each of these actions ans see where we can put them.

**Comment by sorincarbunaru** [comment]
Coming back to this... We already have some of the requests implemented:
- Branch merging
- Reset to commit
- Checkout branch
- Create new branch
- Revert commit

We also have separate issues (either here or on JIRA) for:
- Tagging commits (#49)
- Rebasing (EXM-46341)
- Cherry picking (EXM-48633)
- Showing the branches this commit is on (EXM-48634)

Therefore I am going to close this, and well focus on the more specific issues.

**Comment by kirkilj** [comment]
Thanks for the follow up. We're looking forward to 2.6.
