### ISSUE TITLE
Space between ShapeDivider on section and the element underneeth 

### ISSUE THREAD

**Issue by joerg-99** [oxygenxml/oxygen-git-plugin#97]
There is small space between the ShapeDivide on a section and the element which follows underneeth the section on the mobile view. The background of the section is shown.

Divider Shape on a section (margin top 50)
Under the section are columns (margin 0, padding 20)
Section container padding 0, hight 100%
Divider Shape: Balance 3
Position: Bottom
The background color of the columns is the same like the divider shape

**Comment by joerg-99** [comment]
The space is still there. Why is this closed without a comment?

**Comment by raducoravu** [comment]
Sorry, we were sifting through bugs yesterday and we probably did this by mistake. Can you give us maybe a screenshot presenting the problem? You are discussing about a "mobile view"? What does that mean?

**Comment by qa-joerg** [comment]
No Prob. Hope you can reproduce this anyhow.  Please visit https://www.golfheroes.de/die-helden/ using your smartphone. Please scroll down to the middle of the page. I see this issue on a Iphone 11 pro. 
![gf](https://user-images.githubusercontent.com/56035737/88161544-6688b600-cc10-11ea-90b8-91fdbc4ff3a8.jpg)

**Comment by AlexJitianu** [comment]
This project is about a Git client available inside Oxygen XML Editor. It doesn't have any connection with the space divider from that website.
