### ISSUE TITLE
Notify the user when the local branch is behind the upstream/remote branch

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-plugin#98]
Some people don't like when they get behind the upstream branch because they fear a possible conflict that may arise when they push.

A possible solution that is feasible right now, is to have an option in the preferences page named  _Warn me if I'm behind_ with possible values: 
1. _Always_ : As soon as we see new commits in the remote, we notify the user
2. _On possible conflicts_: If the user opens a file, we check to see if there are remote commits in which that file was changed and we notify the user
3. _Never_

We had user requests for an automatic pull options as well, but it is not clear to me how to do the pull only when there are no conflicts. When I figure that out, I will add a new issue. Until then, I believe users will benefit from a simple notification as well.

## Implementation details:
1. Add a listener on opened editors in the main editing area as well as the DITA Maps Manager. When an editor is opened, a task is scheduled coalescing. We can use {{com.oxygenxml.git.utils.GitOperationScheduler.schedule(Runnable, int)}} to implement this coalescing, by canceling the previous task and putting a new one.
2. When the task executes, it looks at the _Warn me if I'm behind_  option:
2.1 If the value is __On possible conflicts_ . Identify the opened files that are from the git repository. If we have such files, to a Fetch, and search in the commits that come if those files were changed. If the files were changed, notify the user.
2.2 If the value is _Always_, notify the user. The user can pull directly from the dialog.

**Comment by AlexJitianu** [comment]
1. We can have a new class _com.oxygenxml.git.watcher.RepositoryChangeWatcher_ which will be initialized last in  _com.oxygenxml.git.OxygenGitPluginExtension.applicationStarted(StandalonePluginWorkspace)_:
`RepositoryChangeWatcher.initialize(StandalonePluginWorkspace)`

**Comment by AlexJitianu** [comment]
To add an option page for the plugin:
1. You first use the extension point in plugin.xml
`<extension type="OptionPage" `class="my.pack.CustomOptionPagePluginExtension"/>``
2. CustomOptionPagePluginExtension extrends _ro.sync.exml.plugin.option.OptionPagePluginExtension_
2.1 The _getTitle()_ method should return the name of the plugin (defined in _plugin.xml), Git Client, to avoid creating a sub-entry in the options structure.
2.2 The apply method takes the values from the controls and save them inside options.
```
  public void apply(PluginWorkspace pluginWorkspace) {
    // Save the new locations in the option storage.
    pluginWorkspace.getOptionsStorage().setOption(KEY_SAVE_TEMPORARY_FILES_LOCATION,
        !"".equals(saveTmpLocationTextField.getText()) ? saveTmpLocationTextField.getText() : null);
    pluginWorkspace.getOptionsStorage().setOption(KEY_DEFAULT_CHECKOUT_LOCATION,
        !"".equals(defaultCheckoutLocationTextField.getText()) ? defaultCheckoutLocationTextField.getText() : null);
  }
```

**Comment by AlexJitianu** [comment]
User feedback:

**Comment by AlexJitianu** [comment]
Code review:
1. RepositoryChangeListeners.task(String) - If we present to the user a notification, let's remember the top upstream revision commit id (A new flag in the options). A second notification will not be presented as long as the top revision ID is the same. The idea is that the user might not be interested in pulling changes so we shouldn't bother him until something else changes in the remote.
2. I would move everything from RepositoryChangeListeners into RepositoryChangeWatcher. 
3. Comment class RepositoryChangeWatcher, its fields and its methods (for example getFilesFromEditor parameters)
4. RepositoryChangeListeners.checkForRemoteFileChanges() - openedLocalFiles should be a HashSet
5. _RepositoryChangeListeners.checkForRemoteFileChanges()_ - I see that it iterates over _GitAccess.getCommitsCharacteristics(String)_. This method returns all the commits in the repository, both in the current branch and in the upstream branch. All of them. We should iterate just over the 2 or 3 commits that are in the upstream but not in the local. These are the ones that _RepositoryChangeListeners.checkForRemoteCommits()_ returned a little earlier.
6. _RepositoryChangeListeners.checkForRemoteCommits()_ - You need _CommitsAheadAndBehind.getCommitsBehind()_. These are the commit from the upstream that are not yet pulled.

**Comment by AlexJitianu** [comment]
Code review:
1. What I meant at this point was to store the upstream top commit id after we present the notification. This commit id is not something to present in the options page. It is just a value that we store and we take into account in the _task()_ method.
7. There are fields and methods without documentation in _RepositoryChangeWatcher_ and _OptionsManager_
8. _OxygenGitOptionPagePluginExtension.apply(PluginWorkspace)_ is not saving the options properly. It should not do anyhting with _pluginWorkspace.getOptionsStorage()_ directly, but through _OptionsManager.getInstance()_. Also, in _OptionsManager.getInstance()_ we must pass to _setWarnOnUpstreamChange()_ a value depending on which radio button is selected.

**Comment by AlexJitianu** [comment]
Code review.
1. When pulling, have a look inside _com.oxygenxml.git.view.ToolbarPanel.PullAction.actionPerformed(ActionEvent)_. I suggest we do thing similarly because:
1.1 The user might have activated a pull with rebase mode
1.2 _PushPullController_ is a higher level API that better handles exceptions. 
Right now an instance of __PushPullController_  in created inside _com.oxygenxml.git.view.StagingPanel.createPushPullController()_. I suggest creating the instance earlier, inside _OxygenGitPluginExtension_ and pass it as a parameter to both the _StagingPanel_ constructor and the _RepositoryChangeWatcher_
2. I'm thinking to have the messages like this:

> [T] Remote changes detected
> 
> New commits were detected in the remote repository. It is recommended to pull these changes into the local repository to avoid future conflicts.
> 
> Do you want to pull the remote changes into the local repository?
> 
> [Yes], [No]
> 
> 
> 
> [T] Remote changes detected
> 
> The following files changed in the remote repository. 
> 
> file1.txt
> file2.txt
> 
> It is recommended to pull the remote changes to avoid future conflicts.
> 
> Do you want to pull the remote changes into the local repository?
> 
> [Yes], [No]

The list of files should be put in a scroll pane. perhaps we can make _com.oxygenxml.git.view.dialog.PullStatusAndFilesDialog_ a little more generic and use it. it presents a message and a list of file. it probably needs a second message, to be presented under the list of files.

**Comment by AlexJitianu** [comment]
I have 2 more things that I noticed:
1. If the user chooses to pull and the current selected editor is one of the one changed in the remote, it looks like we need to use the API to reload the editor. It is important to do so because otherwise you might start making changes in it while the version on disk is modified.

2. We should store that commit id per repository. We now have a global value, the the id depends on the repository. Instead od a plain string we need a map of string (repository absolute path) to string (commit id).

**Comment by AlexJitianu** [comment]
Code review:
1. In _Options_ the newly added methods lack documentation. Also, it is recommended for methods to return an interface rather than an implementation. The below method can return `Map<String, String>`
` public HashMap<String, String> getWarnOnCommitIdChange() {`
Anyway, we can just remove this method since it's only used internally.
2. _warnOnCommitIdChange_ - _warnOnChangeCommitId_ makes more sense. The methods that work with it should also be renamed
3. In _getWarnOnCommitIdChange()_ - document the _repositoryId_ parameter that should be obtained using _org.eclipse.jgit.lib.Repository.getIdentifier()_. Instead of putting an empty string in the map, we can just use: 
`warnOnCommitIdChange.getOrDefault(repositoryId, "")`
4.

**Comment by AlexJitianu** [comment]
I presented the issue internally and we decided to:
- We will have just one option, a check box "Notify me about new commits in the remote repository"
- We will present the generic notification. The name of the buttons: _Pull changes_ and _Close_

**Comment by sorincarbunaru** [comment]
Code review on the last commit:
- I think we should remove the "Notifications for new commits in the remote "label
- The component corresponding to the option should be a JCheckBox instead of JRadioButton. Radio buttons are used when you have to choose one option from multiple ones.
- `warnOnNewCommitsCheckBox` should be something like `notifyAboutRemoteCommitsCheckBox`, because the options does not show a warning, but a pice of information (a notification). In a similar way and for the same reason, we should change `warnOnUpstreamChange`, `getWarnOnUpstreamChange()` and whatever names are there in something that doesn't say "warning".
- Isn't `private boolean warnOnUpstreamChange = false;` redundant? The default values of boolean fields is `false`.
- Instead of `warnOnUpstreamChange == false` you could simply use `!warnOnUpstreamChange `, or event better, use `warnOnUpstreamChange` and change the order of the operations.
- `boolean value = ...` should be something like `boolean isNotifyAboutRemoteCommits` or something like that, everywhere. Booleans should use this `isSomething` convention.
